name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Flutter Project
    runs-on: macos-latest

    env:
      FLUTTER_VERSION: 3.22.1

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Install Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release
      env:
        CI: true

    - name: Build IPA
      run: |
        flutter build ios --release --no-codesign
      env:
        CI: true

    - name: Archive APK
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Archive IPA
      uses: actions/upload-artifact@v2
      with:
        name: ios-ipa
        path: build/ios/iphoneos/Runner.app
